spring.profiles.active=dev

spring.application.name=platforme-tegg

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

server.port=8080

jwt.secret=TeggSecretKeyForJWTTokenGeneration2024MustBeLongEnough
jwt.expiration-ms=86400000

logging.level.sn.tegg.platforme=DEBUG
logging.level.org.springframework.security=DEBUG
